### ISSUE TITLE
Problema con UTF8 desde el canal IRC

### ISSUE THREAD

**Issue by Kazbayadum** [stenyak/breakbot#1]
Hola

Hay un problema a la hora de detectar las "ñ" y las tíldes en el IRC. Al transcribirlas al wa aparecen como "interrogaciones blancas dentro de un rombo negro", que es un símbolo que imagino que utiliza cuando no tiene ni idea de lo que ve.

A mí se me ocurre que puede ser porque escribo en UTF8 en la sala de IRC, porque me ha pasado más veces.

Gracias señor con barba.

**Comment by stenyak** [comment]
Confirmed, bot logs show the problem:

`2012-11-15 03:17:17.628273: Gateway:  <<< Received IRC message: 1352945837628124: atenea in #asekas said to None: si q ya es tarde ene spaña
ingnored toString call, encountered unicode error                                                                                        
2012-11-15 03:17:17.628993: Gateway: Channel #asekas not recognized: 'ascii' codec can't decode byte 0xc3 in position 33: ordinal not in range(128)`
