### ISSUE TITLE
Issue runnning get_libs.sh 

### ISSUE THREAD

**Issue by lightonphiri** [stenyak/breakbot#12]
I ran into the following error when executing get_libs.sh

phiri@HP-ProBook-4520s:~/Projects/ossproj/breakbot$ ./get_libs.sh 
A    oyoyo/parse.py
A    oyoyo/client.py
A    oyoyo/**init**.py
A    oyoyo/examplebot.py
A    oyoyo/cmdhandler.py
A    oyoyo/ircevents.py
A    oyoyo/helpers.py
Checked out revision 55.
Cloning into 'yowsup.git'...
Warning: Permanently added the RSA host key for IP address '192.30.252.130' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:stenyak/yowsup.git' into submodule path 'yowsup.git' failed
phiri@HP-ProBook-4520s:~/Projects/ossproj/breakbot$ cat get_libs.sh

**Comment by stenyak** [comment]
Hi phiri,
I'm experiencing the same issue in all my github repositories. I don't know the reason for this (yet), meanwhile here's a workaround:
1. Open the .gitmodules file
2. Replace the yowsup url with this one instead: `https://github.com/stenyak/yowsup.git`
3. Save file
4. Try again to run ./get_libs.sh

**Comment by lightonphiri** [comment]
Hello stenyak,

Thank you for this. I couldn't get past the error though; I had to change submodule URL in repository config file as well.

phiri@HP-ProBook-4520s:~/Projects/ossproj/breakbot/.git$ cat config 
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[remote "origin"]
        url = https://github.com/stenyak/breakbot.git
        fetch = +refs/heads/_:refs/remotes/origin/_
[branch "master"]
        remote = origin
        merge = refs/heads/master
[submodule "yowsup.git"]
        url = git@github.com:stenyak/yowsup.git
phiri@HP-ProBook-4520s:~/Projects/ossproj/breakbot/.git$ vi config
