### ISSUE TITLE
Not joining channels

### ISSUE THREAD

**Issue by h1rule** [stenyak/breakbot#13]
Hey guys,

the whatsapp bot does not join irc channels.
and:

can you set a irc channel for each private message user?

Greetings!

**Comment by stenyak** [comment]
Can you please explain in more detail what exactly you are trying to do?
Also, if the breakbot logs show errors, please attach them or copy-paste them here.

Thanks!

**Comment by h1rule** [comment]
Ok so here we go. I've installed everything told on the step by step installation tutorial.

my config:

http://paste.capsload.it/1055/38963350/raw/

I've replaced some personal informations with 'X'

When i run the bot: ./bot.py

http://paste.capsload.it/1054/63341613/raw/

Its not joining the channels.

**Comment by stenyak** [comment]
Interesting... please check these two things:
1) Confirm that the bot is also configured as a contact in the "contacts" section of config.json, with correct phone number.
2) Temporarily try using irc.freenode.net on port 6667. This is to check that your server is not doing something different than freenode (which is the server that has never failed in my tests).

**Comment by h1rule** [comment]
1) confirmed.
2) tested and confirmed the work. its network depencies. its working on irc.rizon.net. :+1: 

Thank you sir!

**Comment by stenyak** [comment]
Glad to hear it works :-)

**Comment by h1rule** [comment]
But this would be great if its working with other networks such aus unrealircd.
I am currently using my private network with unrealircd, but its not joining the channels again there :(.
Could you update it? :)

**Comment by stenyak** [comment]
Sorry, I thought that the problem was on your server and that you had already fixed it.
I'll keep this ticket open, and will try to find time to debug the issue some day. If you find more details about the problem (irc server logs, or whatever), please let me know.

**Comment by h1rule** [comment]
No problem :).

As i told, it depense on the IRC server protocol.

freenode -> working
irc.rizon.net -> working
irc.quakenet.org -> not working
unrealircd -> not working ( irc.capsload.it ) -> most important for me personal.

When i force the Bot to join a channel, its simply not sending the messages.
I think its just the way the different IRC Server softwares getting and handling the commands.

Nice work tho with your WhatsApp Bot.

What do you think about IRC Channels for private messages too?

:)

**Comment by stenyak** [comment]
Do those servers have something in common? (e.g. all working servers use XYZ irc software, while non-working use ABC software).

Private messages are currently handled without needing channels, they are directed at the bot_owner_nick (as per config.json) , though admitedly I haven't used it for a long time and am not sure if it's still working. Please open a new issue for this question/featurerequest.

**Comment by h1rule** [comment]
irc.rizon.net - running version hybrid-7.2.3+plexus-3.1.0(20130523_0-539)
irc.quakenet.org - running version u2.10.12.10+snircd(1.3.4a)
irc.capsload.it - running version Unreal3.2.8.1
irc.freenode.net - running version ircd-seven-1.1.3

**Comment by h1rule** [comment]
I think it could have anything to do with responding to the PING sent by the IRC network with a PONG before actually are able to do any commands (like joining channels).

**Comment by stenyak** [comment]
You were correct, PINGs were the source of the problem. I've implemented a wait-for-ping functionality, and I'm now able to join both freenode and quakenet.

Please check the latest version and let me know if you have any further problems.

**Comment by h1rule** [comment]
Confirmed working. Thank you!

**Comment by stenyak** [comment]
You're welcome :)
