### ISSUE TITLE
Trying to generate a multiple bot :P

### ISSUE THREAD

**Issue by h1rule** [stenyak/breakbot#15]
Hey guys

just running 2 Whatsapp Bots.

My goal:

-> Both bots are in the same group
-> Both bots are in the same IRC channel
-> Generating a "spam" each other, to test whatsapp's anti-spam protection.

The problem is:

Every message, the message gets larger:

 <WhatsAppBot> <WhatsAppBot2> <WhatsAppBot> <WhatsAppBot2> <WhatsAppBot> <WhatsAppBot2> <WhatsAppBot> <WhatsAppBot2> <WhatsAppBot> <WhatsAppBot2> <WhatsAppBot> <WhatsAppBot2> <WhatsAppBot> <WhatsAppBot2> <WhatsAppBot> <WhatsAppBot2> <WhatsAppBot> <WhatsAppBot2> <WhatsAppBot> <WhatsAppBot2> <WhatsAppBot> <WhatsAppBot2> <WhatsAppBot> <WhatsAppBot2> <WhatsAppBot> <WhatsAppBot2> <WhatsAppBot> <WhatsAppBot2> <WhatsAppBot> <WhatsAppB

Where can i edit the output of the bot?
It should just send the message, not from who

(so basicly: just remove the senders name)

<Whatsapp> Hi

next message

<Whatsapp2> <Whatsapp> Hi

and contiunleys: thats bad!

It just should send "hi" :)

What to edit in the .py scripts?

**Comment by stenyak** [comment]
What you are seeing is the expected behaviour, the bot is simply quoting the other participants.

If you want to remove the quoting (i.e. leave quoted texts verbatim), edit bot.py, look for strings that contain `<%s>` in them (which is the <nickname> prefixed to each message), and remove it.

**Comment by h1rule** [comment]
alright, i removed all <%s> but now the bot cant catch or handle any messages.
what lines do i have to remove excatley for this:
- No "< Nickname >" in Whatsapp Group
- No "< Nickname >" in IRC Channel

But text should be visible.

Uploaded a image for the original bot.py

http://www.capsload.it/images/1390914219.png
(After like 10 lines, it stops because the message will be too long)

It should be like this:
http://www.capsload.it/images/1390914347.png
(unlimited, because just the text is catched + sent)

**Comment by stenyak** [comment]
Remove all strings that say `<%s>`. You must of course adapt the formatting parameters.

This is basic python, you need to learn python in order to be able to correctly modify the python code of the bot.
http://www.diveintopython.net/native_data_types/formatting_strings.html

**Comment by h1rule** [comment]
I dont get it :(.

Could you upload a bot.py without the Nicknames?

Its really important. I tried it since 6 hours. Always getting some kinds of errors.

**Comment by ozbek** [comment]
This deserves a smiley: ^^

**Comment by stenyak** [comment]
@capsload you replied to my comment not even 5 minutes after reading it. Unfortunately I don't have the time to teach random Internet peoples how to program ;-)

Please, at least check the link I kindly provided in my previous comment. If you still have problems after that, search the web for more information about python, or ask at any programming/python forum.
