### ISSUE TITLE
Send Message to NON-Contacts

### ISSUE THREAD

**Issue by h1rule** [stenyak/breakbot#21]
Hello,

what about sending Messages to numbers?

Instead of /msg Bot Nick: Hi

Just /msg Bot 01234566: Hi

So you can send to everyone and not have them in the config + restarting the bot everytime.

**Comment by stenyak** [comment]
This was supposed to have been working since forever, but I hadn't actually tested it properly. It had a couple bugs, which are fixed, and it now Works On My Computer (tm).

I'm closing this, but if you encounter any further issue, feel free to let me know.

**Comment by h1rule** [comment]
ImportError: cannot import name warning

When trying to start the ./bot.py after upgrading to the new files.
