### ISSUE TITLE
ImportError: cannot import name warning

### ISSUE THREAD

**Issue by h1rule** [stenyak/breakbot#23]
root@whatsappxploit:~/link103# ./bot.py
Traceback (most recent call last):
  File "./bot.py", line 9, in <module>
    from log import info, error, warning
ImportError: cannot import name warning

Using latest versions.

**Comment by h1rule** [comment]
Just removed "warning" in the first lines from bot.py

Now:

NameError: global name 'warning' is not defined

2014-07-12 13:12:05.385813 EE catch_them_all.py:12: Exception in function irc_msg_received

**Comment by stenyak** [comment]
There's something fishy here. Can you please do a fresh git clone in a different place, run get_libs and the usual stuff, copy your existing config.json file over there, and try again?

**Comment by h1rule** [comment]
Nice! 
Its working like that. 

:)

**Comment by stenyak** [comment]
Good to know :)
