### ISSUE TITLE
Syntax error with bot.py

### ISSUE THREAD

**Issue by rmNULL** [stenyak/breakbot#33]
> > python bot.py
> >     File "bot.py", line 95
> >     except Exception, e:
> >                                ^  
> > SyntaxError: invalid syntax
> > ![screenshot](https://cloud.githubusercontent.com/assets/8173131/8333299/f0a922c4-1aaf-11e5-9c77-5a38c4a4c089.png)

**Comment by Jzarecta** [comment]
Looks a bit like a python version issue.
Make sure you are on the right python version 2.x or 3.x
