### ISSUE TITLE
doesn't mirror messages with umlauts or emoji in it

### ISSUE THREAD

**Issue by bl1nk** [stenyak/breakbot#6]
If a message contains an umlaut (üöäß) or emoji it doesn't get mirrored to IRC

**Comment by stenyak** [comment]
I'm not able to replicate the error on my side: I've been able to send and receive those 4 characters (üöäß) to and from IRC without any problem.

Can you please attach the relevant last lines of bot.log, after you've triggered the error?

Thanks!
