### ISSUE TITLE
does not start correctly with default setup and tutorial

### ISSUE THREAD

**Issue by NotAFile** [stenyak/breakbot#9]
The bot can't find Yowsup.connectionmanager.YowsupConnectionManager in it's default configuration. This is due to the Yowsup folder being named yowsup.git instead of Yowsup. it's pretty minor, but I just wanted to give you a heads-up

**Comment by NotAFile** [comment]
Also, yowsup.git is empty, which is the core problem.

**Comment by stenyak** [comment]
Thanks for the heads up, this should fix it.
